apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: missing-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-retain
  resources:
    requests:
      storage: 1Gi
